### ISSUE TITLE
오타 수정 + 읽기 좋도록 <br> 추가 등을 제언해도 괜찮을까요?

### ISSUE THREAD

**Issue by heumsi** [Yosseulsin-JOB/Google-Python-Style-Guide-kor#11]
안녕하세요.  
구글 스타일 가이드 문서 번역본 감사히 잘 읽고 있습니다.  
읽다보니 몇몇 오탈자가 보이는데, 이 부분 수정해서 PR 드려도 될까요?
더불어, 마크다운 특성상 문단이 다 빡빡하게 채워져 있는데, <br> 태그로 문단 끼리 조금 나눌 수 있을 거 같습니다.
이렇게 되면 눈이 덜 아프고, 더 읽기 좋은 문서가 될 거 같은데 이 부분도 PR 에 포함해도 괜찮으련지요??

**Comment by Sotaneum** [comment]
@heumsi 안녕하세요 이슈 감사드려요 : )

넵, 요청주시면 확인 후 반영하겠습니다 : )

cc. @0113bernoyoun  @denmark111

**Comment by Sotaneum** [comment]
@heumsi  작업 해주신 내용 반영 되었습니다. : ) [README](https://github.com/Yosseulsin-JOB/Google-Python-Style-Guide-kor/blob/master/Google%20Python%20Style%20Guide%20kor.md)
