### ISSUE TITLE
새로운 번역 제시

### ISSUE THREAD

**Issue by Sotaneum** [Yosseulsin-JOB/Google-Python-Style-Guide-kor#17]
- 약 한달간 하루 1-2시간 정도 필요한 리눅스 시스템 관리자 교육과정인데 무료로 전환됨
- 우리도 공부하면서 변역하면 좋을 듯
- 의견 부탁드립니다.
- https://github.com/snori74/linuxupskillchallenge

**Comment by 0113bernoyoun** [comment]
따로 동영상은 필요 없고 각 파일들을 챕터별로 따라하면 되는 과정인가요?

**Comment by Sotaneum** [comment]
> 따로 동영상은 필요 없고 각 파일들을 챕터별로 따라하면 되는 과정인가요?

넹 없습니다.

@0113bernoyoun

**Comment by 0113bernoyoun** [comment]
@Sotaneum 
AWS 프리티어가 필요한데 이미 프리티어를 소진한 사람은 새로운 방법을 연구해보아야겠군요..

**Comment by Sotaneum** [comment]
@0113bernoyoun 
VMware 같은 가상머신으로 환경 구성하고 SSH로 접근 가능하게 하면 크게 문제 없이 따라 할 수 있을 것 같습니다.
아니면 docker라도...

**Comment by Sotaneum** [comment]
pass!
