### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by sloth0317** [Yosseulsin-JOB/Google-Python-Style-Guide-kor#6]
3.9 클래스.md에 나오는 클래스 부분에 네스티드 클래스보단 중첩클래스로 번역하는게 좀 더 매끄러운 번역이 되지 않을까 생각이 듭니다. 이슈를 읽어주셔서 감사합니다.

**Comment by denmark111** [comment]
중첩클래스 로 수정완료했습니다
이슈 감사드려요~
