### ISSUE TITLE
3.3 Parentheses 부분에서

### ISSUE THREAD

**Issue by sloth0317** [Yosseulsin-JOB/Google-Python-Style-Guide-kor#7]
괄호를 드물게 사용하세요. 보단 괄호를 아껴서 사용하세요. 괄호를 적게 사용하세요. 정도가 더 매끄러운 번역이 될 것 같습니다. 이슈를 읽어 주셔서 감사합니다.

**Comment by denmark111** [comment]
적게 로 수정완료했습니다
이슈 감사드려요~
